app: 
  name: Spring Product Service
server:
  port: 8081
  servlet:
    context-path: /product
application:
  product:
    inventory: 
      url: localhost:8082/inventory/products

spring.cloud.openfeign.circuitbreaker: 
  enabled: true
